export interface Country {
  name: string;
  code: string;
  flag: string;
}

export const countries: Country[] = [
  { name: "United States", code: "US", flag: "🇺🇸" },
  { name: "United Kingdom", code: "GB", flag: "🇬🇧" },
  { name: "Canada", code: "CA", flag: "🇨🇦" },
  { name: "Australia", code: "AU", flag: "🇦🇺" },
  { name: "Germany", code: "DE", flag: "🇩🇪" },
  { name: "France", code: "FR", flag: "🇫🇷" },
  { name: "Netherlands", code: "NL", flag: "🇳🇱" },
  { name: "Sweden", code: "SE", flag: "🇸🇪" },
  { name: "Norway", code: "NO", flag: "🇳🇴" },
  { name: "Denmark", code: "DK", flag: "🇩🇰" },
  { name: "Finland", code: "FI", flag: "🇫🇮" },
  { name: "Ireland", code: "IE", flag: "🇮🇪" },
  { name: "Switzerland", code: "CH", flag: "🇨🇭" },
  { name: "Austria", code: "AT", flag: "🇦🇹" },
  { name: "Belgium", code: "BE", flag: "🇧🇪" },
  { name: "Spain", code: "ES", flag: "🇪🇸" },
  { name: "Portugal", code: "PT", flag: "🇵🇹" },
  { name: "Italy", code: "IT", flag: "🇮🇹" },
  { name: "Poland", code: "PL", flag: "🇵🇱" },
  { name: "Czech Republic", code: "CZ", flag: "🇨🇿" },
  { name: "Romania", code: "RO", flag: "🇷🇴" },
  { name: "Hungary", code: "HU", flag: "🇭🇺" },
  { name: "Greece", code: "GR", flag: "🇬🇷" },
  { name: "Turkey", code: "TR", flag: "🇹🇷" },
  { name: "Israel", code: "IL", flag: "🇮🇱" },
  { name: "United Arab Emirates", code: "AE", flag: "🇦🇪" },
  { name: "Saudi Arabia", code: "SA", flag: "🇸🇦" },
  { name: "India", code: "IN", flag: "🇮🇳" },
  { name: "China", code: "CN", flag: "🇨🇳" },
  { name: "Japan", code: "JP", flag: "🇯🇵" },
  { name: "South Korea", code: "KR", flag: "🇰🇷" },
  { name: "Singapore", code: "SG", flag: "🇸🇬" },
  { name: "Hong Kong", code: "HK", flag: "🇭🇰" },
  { name: "Taiwan", code: "TW", flag: "🇹🇼" },
  { name: "Thailand", code: "TH", flag: "🇹🇭" },
  { name: "Vietnam", code: "VN", flag: "🇻🇳" },
  { name: "Indonesia", code: "ID", flag: "🇮🇩" },
  { name: "Philippines", code: "PH", flag: "🇵🇭" },
  { name: "Malaysia", code: "MY", flag: "🇲🇾" },
  { name: "New Zealand", code: "NZ", flag: "🇳🇿" },
  { name: "Brazil", code: "BR", flag: "🇧🇷" },
  { name: "Mexico", code: "MX", flag: "🇲🇽" },
  { name: "Argentina", code: "AR", flag: "🇦🇷" },
  { name: "Colombia", code: "CO", flag: "🇨🇴" },
  { name: "Chile", code: "CL", flag: "🇨🇱" },
  { name: "South Africa", code: "ZA", flag: "🇿🇦" },
  { name: "Nigeria", code: "NG", flag: "🇳🇬" },
  { name: "Kenya", code: "KE", flag: "🇰🇪" },
  { name: "Egypt", code: "EG", flag: "🇪🇬" },
  { name: "Morocco", code: "MA", flag: "🇲🇦" },
  { name: "Ukraine", code: "UA", flag: "🇺🇦" },
  { name: "Russia", code: "RU", flag: "🇷🇺" },
  { name: "Estonia", code: "EE", flag: "🇪🇪" },
  { name: "Latvia", code: "LV", flag: "🇱🇻" },
  { name: "Lithuania", code: "LT", flag: "🇱🇹" },
  { name: "Croatia", code: "HR", flag: "🇭🇷" },
  { name: "Serbia", code: "RS", flag: "🇷🇸" },
  { name: "Bulgaria", code: "BG", flag: "🇧🇬" },
  { name: "Slovakia", code: "SK", flag: "🇸🇰" },
  { name: "Slovenia", code: "SI", flag: "🇸🇮" },
  { name: "Luxembourg", code: "LU", flag: "🇱🇺" },
  { name: "Iceland", code: "IS", flag: "🇮🇸" },
  { name: "Pakistan", code: "PK", flag: "🇵🇰" },
  { name: "Bangladesh", code: "BD", flag: "🇧🇩" },
  { name: "Sri Lanka", code: "LK", flag: "🇱🇰" },
  { name: "Peru", code: "PE", flag: "🇵🇪" },
  { name: "Ecuador", code: "EC", flag: "🇪🇨" },
  { name: "Uruguay", code: "UY", flag: "🇺🇾" },
  { name: "Costa Rica", code: "CR", flag: "🇨🇷" },
  { name: "Panama", code: "PA", flag: "🇵🇦" },
  { name: "Ghana", code: "GH", flag: "🇬🇭" },
  { name: "Tanzania", code: "TZ", flag: "🇹🇿" },
  { name: "Ethiopia", code: "ET", flag: "🇪🇹" },
  { name: "Qatar", code: "QA", flag: "🇶🇦" },
  { name: "Kuwait", code: "KW", flag: "🇰🇼" },
  { name: "Bahrain", code: "BH", flag: "🇧🇭" },
  { name: "Oman", code: "OM", flag: "🇴🇲" },
  { name: "Jordan", code: "JO", flag: "🇯🇴" },
  { name: "Lebanon", code: "LB", flag: "🇱🇧" },
];

export function findCountry(name: string): Country | undefined {
  return countries.find(c => c.name === name);
}
