import { Meeting } from "./types";

export const mockMeetings: Meeting[] = [
  {
    id: "1",
    inviteeName: "Ryan Sullivan",
    inviteeEmail: "ryan@podcastprinciples.com",
    company: "Podcast Principles",
    meetingDate: new Date(2026, 1, 5),
    meetingTime: "6:00 pm",
    bookedBy: "Alex Thompson",
    bookedAt: new Date(2026, 1, 3, 19, 41),
    calendar: "Sales Team",
    closer: "Sarah Chen",
    rescheduleCount: 0,
    callStage: "Discovery",
    leadStatus: "Potential",
    callStatus: "Booked",
    takenStatus: "Upcoming",
    billingStatus: "Not Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Ryan! Thanks for your interest in our platform. Would love to schedule a quick call to discuss your podcast growth needs.", timestamp: new Date(2026, 1, 1, 10, 30) },
      { id: "2", sender: "them", message: "Hey! Yes, I've been looking for a solution to help scale my podcast. What times work for you?", timestamp: new Date(2026, 1, 1, 14, 15) },
      { id: "3", sender: "us", message: "Great! I have availability on Thursday at 6pm. Does that work for you?", timestamp: new Date(2026, 1, 2, 9, 0) },
      { id: "4", sender: "them", message: "Thursday at 6pm works perfectly. Looking forward to it!", timestamp: new Date(2026, 1, 2, 11, 30) },
      { id: "5", sender: "us", message: "Perfect! I've sent over the calendar invite. See you then!", timestamp: new Date(2026, 1, 3, 19, 41) },
    ],
  },
  {
    id: "2",
    inviteeName: "Mark Bishop",
    inviteeEmail: "mark@markbishopmedia.com",
    company: "Mark Bishop Media",
    meetingDate: new Date(2026, 1, 5),
    meetingTime: "5:00 pm",
    bookedBy: "James Wilson",
    bookedAt: new Date(2026, 1, 3, 16, 13),
    calendar: "Enterprise",
    closer: "Emily Davis",
    rescheduleCount: 1,
    callStage: "Discovery",
    leadStatus: "Potential",
    callStatus: "Rescheduled",
    takenStatus: "Shown",
    billingStatus: "Not Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Mark! I noticed your media company has been doing amazing work. Would you be open to a quick chat about how we could help?", timestamp: new Date(2026, 0, 3, 11, 0) },
      { id: "2", sender: "them", message: "Thanks for reaching out! What specifically does your platform offer?", timestamp: new Date(2026, 0, 3, 15, 30) },
      { id: "3", sender: "us", message: "We help media companies streamline their content distribution and grow their audience. Happy to walk you through a demo!", timestamp: new Date(2026, 0, 4, 9, 15) },
      { id: "4", sender: "them", message: "Sounds interesting. Can we do Thursday at 5pm?", timestamp: new Date(2026, 0, 4, 14, 0) },
      { id: "5", sender: "us", message: "Thursday at 5pm is booked! Looking forward to showing you what we've built.", timestamp: new Date(2026, 0, 5, 16, 13) },
    ],
  },
  {
    id: "3",
    inviteeName: "Michael Schwarcz",
    inviteeEmail: "mikeschwarcz@rowfive.co",
    company: "Row Five",
    meetingDate: new Date(2026, 1, 4),
    meetingTime: "6:00 pm",
    bookedBy: "Alex Thompson",
    bookedAt: new Date(2026, 1, 2, 23, 58),
    calendar: "Sales Team",
    closer: "Sarah Chen",
    rescheduleCount: 0,
    callStage: "Discovery",
    leadStatus: "Qualified",
    callStatus: "Booked",
    takenStatus: "Upcoming",
    billingStatus: "Not Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Michael! Saw Row Five's recent growth - impressive work! Would love to connect.", timestamp: new Date(2026, 0, 4, 8, 30) },
      { id: "2", sender: "them", message: "Hey! Thanks for noticing. What's on your mind?", timestamp: new Date(2026, 0, 4, 12, 45) },
      { id: "3", sender: "us", message: "We've helped similar companies scale their operations. Would a 30-min call work to explore?", timestamp: new Date(2026, 0, 5, 10, 0) },
      { id: "4", sender: "them", message: "Sure, let's do it. Wednesday at 6pm?", timestamp: new Date(2026, 0, 5, 16, 30) },
      { id: "5", sender: "us", message: "Done! Calendar invite on its way.", timestamp: new Date(2026, 0, 5, 23, 58) },
    ],
  },
  {
    id: "4",
    inviteeName: "Arvinth Kumar",
    inviteeEmail: "arvinth@theagency.business",
    company: "The Agency",
    meetingDate: new Date(2026, 1, 4),
    meetingTime: "4:00 pm",
    bookedBy: "Michael Brown",
    bookedAt: new Date(2026, 1, 2, 19, 44),
    calendar: "Enterprise",
    closer: "James Wilson",
    rescheduleCount: 0,
    callStage: "Discovery",
    leadStatus: "Won",
    callStatus: "Booked",
    takenStatus: "Shown",
    billingStatus: "Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Arvinth! Your agency has been on our radar. Would love to discuss a potential partnership.", timestamp: new Date(2026, 0, 3, 14, 0) },
      { id: "2", sender: "them", message: "Interesting timing - we've actually been looking for solutions in this space.", timestamp: new Date(2026, 0, 4, 9, 30) },
      { id: "3", sender: "us", message: "Perfect! Let's get on a call. Does Tuesday at 4pm work?", timestamp: new Date(2026, 0, 4, 11, 15) },
      { id: "4", sender: "them", message: "Works for me. Send over the details.", timestamp: new Date(2026, 0, 5, 10, 0) },
      { id: "5", sender: "us", message: "All set! Excited to chat with you tomorrow.", timestamp: new Date(2026, 0, 5, 19, 44) },
    ],
  },
  {
    id: "5",
    inviteeName: "Jessica Chen",
    inviteeEmail: "jessica@techstartup.io",
    company: "Tech Startup",
    meetingDate: new Date(2026, 1, 3),
    meetingTime: "2:00 pm",
    bookedBy: "Sarah Chen",
    bookedAt: new Date(2026, 1, 1, 14, 22),
    calendar: "Sales Team",
    closer: "Alex Thompson",
    rescheduleCount: 2,
    callStage: "Demo",
    leadStatus: "Lost - Not Interest",
    callStatus: "Cancelled",
    takenStatus: "Not Shown",
    billingStatus: "Not Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Jessica! Congrats on your recent funding round. Would love to show you how we can help scale your operations.", timestamp: new Date(2026, 0, 6, 10, 0) },
      { id: "2", sender: "them", message: "Thanks! We're quite busy right now but I'm curious. What do you offer?", timestamp: new Date(2026, 0, 6, 16, 45) },
      { id: "3", sender: "us", message: "We provide end-to-end growth solutions. A quick 20-min call would give you a good overview.", timestamp: new Date(2026, 0, 7, 9, 30) },
      { id: "4", sender: "them", message: "Okay, let's try Friday at 2pm.", timestamp: new Date(2026, 0, 7, 14, 0) },
      { id: "5", sender: "us", message: "Booked! Talk soon.", timestamp: new Date(2026, 0, 8, 14, 22) },
      { id: "6", sender: "them", message: "Actually, we've decided to go a different direction. Sorry about that.", timestamp: new Date(2026, 0, 9, 11, 0) },
    ],
  },
  // --- Additional bookings ---
  {
    id: "6",
    inviteeName: "Kyle Deever",
    inviteeEmail: "kyle@badbetproductions.com",
    company: "Bad Bet Productions",
    meetingDate: new Date(2026, 1, 9),
    meetingTime: "5:00 pm",
    bookedBy: "Alex Thompson",
    bookedAt: new Date(2026, 1, 5, 20, 14),
    calendar: "Sales Team",
    closer: "Sarah Chen",
    rescheduleCount: 0,
    callStage: "Discovery",
    leadStatus: "Potential",
    callStatus: "Booked",
    takenStatus: "Upcoming",
    billingStatus: "Not Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Kyle! Love what Bad Bet Productions is doing. Would be great to connect.", timestamp: new Date(2026, 1, 4, 9, 0) },
      { id: "2", sender: "them", message: "Thanks! Sure, happy to chat.", timestamp: new Date(2026, 1, 4, 14, 30) },
    ],
  },
  {
    id: "7",
    inviteeName: "Sophie Turner",
    inviteeEmail: "sophie@crescentdigital.com",
    company: "Crescent Digital",
    meetingDate: new Date(2026, 1, 9),
    meetingTime: "3:00 pm",
    bookedBy: "Emily Davis",
    bookedAt: new Date(2026, 1, 6, 11, 30),
    calendar: "Enterprise",
    closer: "James Wilson",
    rescheduleCount: 0,
    callStage: "Discovery",
    leadStatus: "Qualified",
    callStatus: "Booked",
    takenStatus: "Upcoming",
    billingStatus: "Not Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Sophie! Crescent Digital caught our eye. Would love to explore synergies.", timestamp: new Date(2026, 1, 5, 10, 0) },
      { id: "2", sender: "them", message: "Sounds great, let's set something up.", timestamp: new Date(2026, 1, 5, 16, 0) },
    ],
  },
  {
    id: "8",
    inviteeName: "Daniel Park",
    inviteeEmail: "daniel@novaventures.co",
    company: "Nova Ventures",
    meetingDate: new Date(2026, 1, 8),
    meetingTime: "11:00 am",
    bookedBy: "James Wilson",
    bookedAt: new Date(2026, 1, 5, 9, 45),
    calendar: "Sales Team",
    closer: "Sarah Chen",
    rescheduleCount: 1,
    callStage: "Demo",
    leadStatus: "Qualified",
    callStatus: "Rescheduled",
    takenStatus: "Upcoming",
    billingStatus: "Pending",
    conversation: [
      { id: "1", sender: "us", message: "Hi Daniel! Nova Ventures' growth has been impressive. Would love to connect.", timestamp: new Date(2026, 1, 3, 14, 0) },
      { id: "2", sender: "them", message: "Appreciate it! What do you have in mind?", timestamp: new Date(2026, 1, 4, 10, 0) },
    ],
  },
  {
    id: "9",
    inviteeName: "Priya Sharma",
    inviteeEmail: "priya@elementstudio.io",
    company: "Element Studio",
    meetingDate: new Date(2026, 1, 8),
    meetingTime: "2:30 pm",
    bookedBy: "Alex Thompson",
    bookedAt: new Date(2026, 1, 6, 15, 20),
    calendar: "Sales Team",
    closer: "Emily Davis",
    rescheduleCount: 0,
    callStage: "Discovery",
    leadStatus: "Potential",
    callStatus: "Booked",
    takenStatus: "Upcoming",
    billingStatus: "Not Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Priya! Element Studio is doing some fantastic work. Would love to chat.", timestamp: new Date(2026, 1, 5, 11, 0) },
      { id: "2", sender: "them", message: "Thanks! I'm open to learning more.", timestamp: new Date(2026, 1, 5, 17, 30) },
    ],
  },
  {
    id: "10",
    inviteeName: "Tom Whitfield",
    inviteeEmail: "tom@whitfieldconsulting.com",
    company: "Whitfield Consulting",
    meetingDate: new Date(2026, 1, 7),
    meetingTime: "10:00 am",
    bookedBy: "Michael Brown",
    bookedAt: new Date(2026, 1, 4, 8, 0),
    calendar: "Enterprise",
    closer: "James Wilson",
    rescheduleCount: 0,
    callStage: "Negotiation",
    leadStatus: "Won",
    callStatus: "Booked",
    takenStatus: "Shown",
    billingStatus: "Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Tom! We'd love to explore how we can support Whitfield Consulting.", timestamp: new Date(2026, 1, 2, 9, 0) },
      { id: "2", sender: "them", message: "Let's do it. Send me a time.", timestamp: new Date(2026, 1, 2, 12, 0) },
    ],
  },
  {
    id: "11",
    inviteeName: "Lara Mendes",
    inviteeEmail: "lara@brightpath.agency",
    company: "Bright Path Agency",
    meetingDate: new Date(2026, 1, 7),
    meetingTime: "4:30 pm",
    bookedBy: "Sarah Chen",
    bookedAt: new Date(2026, 1, 5, 13, 10),
    calendar: "Sales Team",
    closer: "Alex Thompson",
    rescheduleCount: 0,
    callStage: "Discovery",
    leadStatus: "Potential",
    callStatus: "Booked",
    takenStatus: "Upcoming",
    billingStatus: "Not Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Lara! Bright Path has been on our radar. Would be great to connect.", timestamp: new Date(2026, 1, 4, 10, 0) },
      { id: "2", sender: "them", message: "Sure! What's this about?", timestamp: new Date(2026, 1, 4, 15, 0) },
    ],
  },
  {
    id: "12",
    inviteeName: "James Crawford",
    inviteeEmail: "james@crawfordmedia.co.uk",
    company: "Crawford Media",
    meetingDate: new Date(2026, 1, 6),
    meetingTime: "1:00 pm",
    bookedBy: "Emily Davis",
    bookedAt: new Date(2026, 1, 3, 17, 0),
    calendar: "Enterprise",
    closer: "Michael Brown",
    rescheduleCount: 2,
    callStage: "Demo",
    leadStatus: "Qualified",
    callStatus: "Rescheduled",
    takenStatus: "Shown",
    billingStatus: "Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi James! Crawford Media's work is top-notch. Would love to discuss a partnership.", timestamp: new Date(2026, 1, 1, 9, 0) },
      { id: "2", sender: "them", message: "Appreciate the kind words. Let's chat.", timestamp: new Date(2026, 1, 1, 14, 0) },
    ],
  },
  {
    id: "13",
    inviteeName: "Nina Volkov",
    inviteeEmail: "nina@spectrumgroup.com",
    company: "Spectrum Group",
    meetingDate: new Date(2026, 1, 6),
    meetingTime: "3:30 pm",
    bookedBy: "Alex Thompson",
    bookedAt: new Date(2026, 1, 4, 10, 45),
    calendar: "Sales Team",
    closer: "Sarah Chen",
    rescheduleCount: 0,
    callStage: "Discovery",
    leadStatus: "Potential",
    callStatus: "Booked",
    takenStatus: "Upcoming",
    billingStatus: "Not Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Nina! Spectrum Group is doing amazing work. Would love to connect.", timestamp: new Date(2026, 1, 3, 11, 0) },
      { id: "2", sender: "them", message: "Thanks! I'd be happy to learn more.", timestamp: new Date(2026, 1, 3, 16, 0) },
    ],
  },
  {
    id: "14",
    inviteeName: "Chris Nakamura",
    inviteeEmail: "chris@tidelineventures.com",
    company: "Tideline Ventures",
    meetingDate: new Date(2026, 1, 3),
    meetingTime: "11:30 am",
    bookedBy: "James Wilson",
    bookedAt: new Date(2026, 1, 1, 8, 30),
    calendar: "Enterprise",
    closer: "Emily Davis",
    rescheduleCount: 0,
    callStage: "Negotiation",
    leadStatus: "Won",
    callStatus: "Booked",
    takenStatus: "Shown",
    billingStatus: "Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Chris! Tideline's recent round was impressive. We'd love to chat.", timestamp: new Date(2026, 0, 30, 10, 0) },
      { id: "2", sender: "them", message: "Thanks! I'm interested. Let's book something.", timestamp: new Date(2026, 0, 30, 15, 0) },
    ],
  },
  {
    id: "15",
    inviteeName: "Emma Richardson",
    inviteeEmail: "emma@pinehurstdigital.com",
    company: "Pinehurst Digital",
    meetingDate: new Date(2026, 1, 3),
    meetingTime: "9:00 am",
    bookedBy: "Michael Brown",
    bookedAt: new Date(2026, 0, 31, 14, 0),
    calendar: "Sales Team",
    closer: "James Wilson",
    rescheduleCount: 1,
    callStage: "Discovery",
    leadStatus: "Not Qualified",
    callStatus: "Cancelled",
    takenStatus: "Not Shown",
    billingStatus: "Refunded",
    conversation: [
      { id: "1", sender: "us", message: "Hi Emma! Pinehurst Digital is doing great work. Would love to connect.", timestamp: new Date(2026, 0, 29, 10, 0) },
      { id: "2", sender: "them", message: "Thanks but we're not looking at this right now.", timestamp: new Date(2026, 0, 30, 9, 0) },
    ],
  },
  {
    id: "16",
    inviteeName: "Oliver Grant",
    inviteeEmail: "oliver@grantbrothers.co",
    company: "Grant Brothers",
    meetingDate: new Date(2026, 1, 2),
    meetingTime: "4:00 pm",
    bookedBy: "Sarah Chen",
    bookedAt: new Date(2026, 0, 30, 11, 0),
    calendar: "Enterprise",
    closer: "Alex Thompson",
    rescheduleCount: 0,
    callStage: "Discovery",
    leadStatus: "Qualified",
    callStatus: "Booked",
    takenStatus: "Shown",
    billingStatus: "Pending",
    conversation: [
      { id: "1", sender: "us", message: "Hi Oliver! Grant Brothers has been growing fast. Let's talk.", timestamp: new Date(2026, 0, 28, 10, 0) },
      { id: "2", sender: "them", message: "Sounds good, I'm available next week.", timestamp: new Date(2026, 0, 28, 16, 0) },
    ],
  },
  {
    id: "17",
    inviteeName: "Aisha Patel",
    inviteeEmail: "aisha@luminancelab.com",
    company: "Luminance Lab",
    meetingDate: new Date(2026, 1, 2),
    meetingTime: "12:00 pm",
    bookedBy: "Alex Thompson",
    bookedAt: new Date(2026, 0, 30, 16, 30),
    calendar: "Sales Team",
    closer: "Sarah Chen",
    rescheduleCount: 0,
    callStage: "Demo",
    leadStatus: "Potential",
    callStatus: "Booked",
    takenStatus: "Upcoming",
    billingStatus: "Not Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Aisha! Luminance Lab's product line is impressive. Would love to explore a partnership.", timestamp: new Date(2026, 0, 29, 9, 0) },
      { id: "2", sender: "them", message: "I appreciate that! Let's set up a call.", timestamp: new Date(2026, 0, 29, 14, 0) },
    ],
  },
  {
    id: "18",
    inviteeName: "Lucas Ferretti",
    inviteeEmail: "lucas@ironridgemedia.com",
    company: "Ironridge Media",
    meetingDate: new Date(2026, 1, 1),
    meetingTime: "3:00 pm",
    bookedBy: "Emily Davis",
    bookedAt: new Date(2026, 0, 29, 10, 0),
    calendar: "Enterprise",
    closer: "Michael Brown",
    rescheduleCount: 0,
    callStage: "Discovery",
    leadStatus: "Lost - Failed To Close",
    callStatus: "Booked",
    takenStatus: "Shown",
    billingStatus: "Not Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Lucas! Ironridge Media has been producing stellar content. Let's connect.", timestamp: new Date(2026, 0, 27, 10, 0) },
      { id: "2", sender: "them", message: "Hey! Sure, what did you have in mind?", timestamp: new Date(2026, 0, 27, 15, 0) },
    ],
  },
  {
    id: "19",
    inviteeName: "Hannah Brooks",
    inviteeEmail: "hannah@brookscreative.io",
    company: "Brooks Creative",
    meetingDate: new Date(2026, 1, 1),
    meetingTime: "10:30 am",
    bookedBy: "James Wilson",
    bookedAt: new Date(2026, 0, 28, 17, 0),
    calendar: "Sales Team",
    closer: "Emily Davis",
    rescheduleCount: 3,
    callStage: "Discovery",
    leadStatus: "Potential",
    callStatus: "Rescheduled",
    takenStatus: "Upcoming",
    billingStatus: "Not Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Hannah! Brooks Creative has been doing some incredible work. Would love to chat.", timestamp: new Date(2026, 0, 25, 10, 0) },
      { id: "2", sender: "them", message: "Thanks! I keep having to reschedule though, bear with me.", timestamp: new Date(2026, 0, 26, 11, 0) },
    ],
  },
  {
    id: "20",
    inviteeName: "Ethan Morris",
    inviteeEmail: "ethan@apexstrategy.com",
    company: "Apex Strategy",
    meetingDate: new Date(2026, 0, 30),
    meetingTime: "1:00 pm",
    bookedBy: "Michael Brown",
    bookedAt: new Date(2026, 0, 27, 9, 0),
    calendar: "Enterprise",
    closer: "James Wilson",
    rescheduleCount: 0,
    callStage: "Negotiation",
    leadStatus: "Won",
    callStatus: "Booked",
    takenStatus: "Shown",
    billingStatus: "Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Ethan! Apex Strategy is exactly the kind of firm we love to work with.", timestamp: new Date(2026, 0, 25, 9, 0) },
      { id: "2", sender: "them", message: "Thanks! Let's discuss. Friday works for me.", timestamp: new Date(2026, 0, 25, 14, 0) },
    ],
  },
  {
    id: "21",
    inviteeName: "Zara Okonkwo",
    inviteeEmail: "zara@vistapoint.co",
    company: "Vista Point",
    meetingDate: new Date(2026, 0, 30),
    meetingTime: "5:00 pm",
    bookedBy: "Sarah Chen",
    bookedAt: new Date(2026, 0, 28, 12, 0),
    calendar: "Sales Team",
    closer: "Alex Thompson",
    rescheduleCount: 0,
    callStage: "Discovery",
    leadStatus: "Potential",
    callStatus: "Booked",
    takenStatus: "Shown",
    billingStatus: "Pending",
    conversation: [
      { id: "1", sender: "us", message: "Hi Zara! Vista Point's growth trajectory is exciting. Would love to connect.", timestamp: new Date(2026, 0, 26, 10, 0) },
      { id: "2", sender: "them", message: "Sounds interesting! Let's do it.", timestamp: new Date(2026, 0, 26, 16, 0) },
    ],
  },
  {
    id: "22",
    inviteeName: "Marcus Lindqvist",
    inviteeEmail: "marcus@nordicwave.se",
    company: "Nordic Wave",
    meetingDate: new Date(2026, 0, 29),
    meetingTime: "9:30 am",
    bookedBy: "Alex Thompson",
    bookedAt: new Date(2026, 0, 26, 14, 0),
    calendar: "Enterprise",
    closer: "Sarah Chen",
    rescheduleCount: 0,
    callStage: "Demo",
    leadStatus: "Qualified",
    callStatus: "Booked",
    takenStatus: "Shown",
    billingStatus: "Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Marcus! Nordic Wave has been making waves. Pardon the pun — would love to chat.", timestamp: new Date(2026, 0, 24, 10, 0) },
      { id: "2", sender: "them", message: "Ha! Good one. Sure, let's connect.", timestamp: new Date(2026, 0, 24, 15, 0) },
    ],
  },
  {
    id: "23",
    inviteeName: "Rachel Kim",
    inviteeEmail: "rachel@canvasworks.co",
    company: "Canvas Works",
    meetingDate: new Date(2026, 0, 29),
    meetingTime: "2:00 pm",
    bookedBy: "Emily Davis",
    bookedAt: new Date(2026, 0, 27, 10, 0),
    calendar: "Sales Team",
    closer: "Michael Brown",
    rescheduleCount: 1,
    callStage: "Discovery",
    leadStatus: "Not Qualified",
    callStatus: "Cancelled",
    takenStatus: "Not Shown",
    billingStatus: "Refunded",
    conversation: [
      { id: "1", sender: "us", message: "Hi Rachel! Canvas Works' portfolio is stunning. Let's explore some opportunities.", timestamp: new Date(2026, 0, 25, 10, 0) },
      { id: "2", sender: "them", message: "Thanks, but we're going a different direction for now.", timestamp: new Date(2026, 0, 26, 9, 0) },
    ],
  },
  {
    id: "24",
    inviteeName: "David Chen",
    inviteeEmail: "david@startline.io",
    company: "Startline",
    meetingDate: new Date(2026, 0, 28),
    meetingTime: "11:00 am",
    bookedBy: "James Wilson",
    bookedAt: new Date(2026, 0, 25, 16, 0),
    calendar: "Enterprise",
    closer: "Emily Davis",
    rescheduleCount: 0,
    callStage: "Discovery",
    leadStatus: "Potential",
    callStatus: "Booked",
    takenStatus: "Shown",
    billingStatus: "Not Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi David! Startline is an exciting venture. Would love to learn more and see how we can help.", timestamp: new Date(2026, 0, 23, 10, 0) },
      { id: "2", sender: "them", message: "Hey! Sure, always open to a conversation.", timestamp: new Date(2026, 0, 23, 14, 0) },
    ],
  },
  {
    id: "25",
    inviteeName: "Victoria Andersen",
    inviteeEmail: "victoria@polarislabs.com",
    company: "Polaris Labs",
    meetingDate: new Date(2026, 0, 28),
    meetingTime: "4:30 pm",
    bookedBy: "Michael Brown",
    bookedAt: new Date(2026, 0, 26, 11, 0),
    calendar: "Sales Team",
    closer: "James Wilson",
    rescheduleCount: 0,
    callStage: "Negotiation",
    leadStatus: "Qualified",
    callStatus: "Booked",
    takenStatus: "Shown",
    billingStatus: "Pending",
    conversation: [
      { id: "1", sender: "us", message: "Hi Victoria! Polaris Labs' research is groundbreaking. Would love to discuss collaboration.", timestamp: new Date(2026, 0, 24, 10, 0) },
      { id: "2", sender: "them", message: "We've been looking for partners. Let's talk.", timestamp: new Date(2026, 0, 24, 16, 0) },
    ],
  },
];
