import { Meeting } from "./types";

export const mockMeetings: Meeting[] = [
  {
    id: "1",
    inviteeName: "Ryan Sullivan",
    inviteeEmail: "ryan@podcastprinciples.com",
    company: "Podcast Principles",
    meetingDate: new Date(2026, 1, 5),
    meetingTime: "6:00 pm",
    bookedBy: "Alex Thompson",
    bookedAt: new Date(2026, 1, 3, 19, 41),
    calendar: "Sales Team",
    closer: "Sarah Chen",
    rescheduleCount: 0,
    callStage: "Discovery",
    leadStatus: "Potential",
    callStatus: "Booked",
    takenStatus: "Upcoming",
    billingStatus: "Not Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Ryan! Thanks for your interest in our platform. Would love to schedule a quick call to discuss your podcast growth needs.", timestamp: new Date(2026, 1, 1, 10, 30) },
      { id: "2", sender: "them", message: "Hey! Yes, I've been looking for a solution to help scale my podcast. What times work for you?", timestamp: new Date(2026, 1, 1, 14, 15) },
      { id: "3", sender: "us", message: "Great! I have availability on Thursday at 6pm. Does that work for you?", timestamp: new Date(2026, 1, 2, 9, 0) },
      { id: "4", sender: "them", message: "Thursday at 6pm works perfectly. Looking forward to it!", timestamp: new Date(2026, 1, 2, 11, 30) },
      { id: "5", sender: "us", message: "Perfect! I've sent over the calendar invite. See you then!", timestamp: new Date(2026, 1, 3, 19, 41) },
    ],
  },
  {
    id: "2",
    inviteeName: "Mark Bishop",
    inviteeEmail: "mark@markbishopmedia.com",
    company: "Mark Bishop Media",
    meetingDate: new Date(2026, 0, 8),
    meetingTime: "5:00 pm",
    bookedBy: "James Wilson",
    bookedAt: new Date(2026, 0, 5, 16, 13),
    calendar: "Enterprise",
    closer: "Emily Davis",
    rescheduleCount: 1,
    callStage: "Discovery",
    leadStatus: "Potential",
    callStatus: "Rescheduled",
    takenStatus: "Shown",
    billingStatus: "Not Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Mark! I noticed your media company has been doing amazing work. Would you be open to a quick chat about how we could help?", timestamp: new Date(2026, 0, 3, 11, 0) },
      { id: "2", sender: "them", message: "Thanks for reaching out! What specifically does your platform offer?", timestamp: new Date(2026, 0, 3, 15, 30) },
      { id: "3", sender: "us", message: "We help media companies streamline their content distribution and grow their audience. Happy to walk you through a demo!", timestamp: new Date(2026, 0, 4, 9, 15) },
      { id: "4", sender: "them", message: "Sounds interesting. Can we do Thursday at 5pm?", timestamp: new Date(2026, 0, 4, 14, 0) },
      { id: "5", sender: "us", message: "Thursday at 5pm is booked! Looking forward to showing you what we've built.", timestamp: new Date(2026, 0, 5, 16, 13) },
    ],
  },
  {
    id: "3",
    inviteeName: "Michael Schwarcz",
    inviteeEmail: "mikeschwarcz@rowfive.co",
    company: "Row Five",
    meetingDate: new Date(2026, 0, 7),
    meetingTime: "6:00 pm",
    bookedBy: "Alex Thompson",
    bookedAt: new Date(2026, 0, 5, 23, 58),
    calendar: "Sales Team",
    closer: "Sarah Chen",
    rescheduleCount: 0,
    callStage: "Discovery",
    leadStatus: "Qualified",
    callStatus: "Booked",
    takenStatus: "Upcoming",
    billingStatus: "Not Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Michael! Saw Row Five's recent growth - impressive work! Would love to connect.", timestamp: new Date(2026, 0, 4, 8, 30) },
      { id: "2", sender: "them", message: "Hey! Thanks for noticing. What's on your mind?", timestamp: new Date(2026, 0, 4, 12, 45) },
      { id: "3", sender: "us", message: "We've helped similar companies scale their operations. Would a 30-min call work to explore?", timestamp: new Date(2026, 0, 5, 10, 0) },
      { id: "4", sender: "them", message: "Sure, let's do it. Wednesday at 6pm?", timestamp: new Date(2026, 0, 5, 16, 30) },
      { id: "5", sender: "us", message: "Done! Calendar invite on its way.", timestamp: new Date(2026, 0, 5, 23, 58) },
    ],
  },
  {
    id: "4",
    inviteeName: "Arvinth Kumar",
    inviteeEmail: "arvinth@theagency.business",
    company: "The Agency",
    meetingDate: new Date(2026, 0, 6),
    meetingTime: "4:00 pm",
    bookedBy: "Michael Brown",
    bookedAt: new Date(2026, 0, 5, 19, 44),
    calendar: "Enterprise",
    closer: "James Wilson",
    rescheduleCount: 0,
    callStage: "Discovery",
    leadStatus: "Won",
    callStatus: "Completed",
    takenStatus: "Shown",
    billingStatus: "Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Arvinth! Your agency has been on our radar. Would love to discuss a potential partnership.", timestamp: new Date(2026, 0, 3, 14, 0) },
      { id: "2", sender: "them", message: "Interesting timing - we've actually been looking for solutions in this space.", timestamp: new Date(2026, 0, 4, 9, 30) },
      { id: "3", sender: "us", message: "Perfect! Let's get on a call. Does Tuesday at 4pm work?", timestamp: new Date(2026, 0, 4, 11, 15) },
      { id: "4", sender: "them", message: "Works for me. Send over the details.", timestamp: new Date(2026, 0, 5, 10, 0) },
      { id: "5", sender: "us", message: "All set! Excited to chat with you tomorrow.", timestamp: new Date(2026, 0, 5, 19, 44) },
    ],
  },
  {
    id: "5",
    inviteeName: "Jessica Chen",
    inviteeEmail: "jessica@techstartup.io",
    company: "Tech Startup",
    meetingDate: new Date(2026, 0, 10),
    meetingTime: "2:00 pm",
    bookedBy: "Sarah Chen",
    bookedAt: new Date(2026, 0, 8, 14, 22),
    calendar: "Sales Team",
    closer: "Alex Thompson",
    rescheduleCount: 2,
    callStage: "Demo",
    leadStatus: "Lost - Not Interest",
    callStatus: "Cancelled",
    takenStatus: "Not Shown",
    billingStatus: "Not Billed",
    conversation: [
      { id: "1", sender: "us", message: "Hi Jessica! Congrats on your recent funding round. Would love to show you how we can help scale your operations.", timestamp: new Date(2026, 0, 6, 10, 0) },
      { id: "2", sender: "them", message: "Thanks! We're quite busy right now but I'm curious. What do you offer?", timestamp: new Date(2026, 0, 6, 16, 45) },
      { id: "3", sender: "us", message: "We provide end-to-end growth solutions. A quick 20-min call would give you a good overview.", timestamp: new Date(2026, 0, 7, 9, 30) },
      { id: "4", sender: "them", message: "Okay, let's try Friday at 2pm.", timestamp: new Date(2026, 0, 7, 14, 0) },
      { id: "5", sender: "us", message: "Booked! Talk soon.", timestamp: new Date(2026, 0, 8, 14, 22) },
      { id: "6", sender: "them", message: "Actually, we've decided to go a different direction. Sorry about that.", timestamp: new Date(2026, 0, 9, 11, 0) },
    ],
  },
];
