// Mock data for Engagement analytics

export const weekdayReplyData = [
  { day: "Mon", avgReplyTime: 4.2, replies: 145 },
  { day: "Tue", avgReplyTime: 3.8, replies: 168 },
  { day: "Wed", avgReplyTime: 5.1, replies: 132 },
  { day: "Thu", avgReplyTime: 4.5, replies: 156 },
  { day: "Fri", avgReplyTime: 6.2, replies: 98 },
  { day: "Sat", avgReplyTime: 8.4, replies: 34 },
  { day: "Sun", avgReplyTime: 9.1, replies: 22 },
];

export const hourlyReplyData: Record<string, { hour: string; replies: number }[]> = {
  Mon: [
    { hour: "6am", replies: 2 }, { hour: "7am", replies: 5 }, { hour: "8am", replies: 12 },
    { hour: "9am", replies: 28 }, { hour: "10am", replies: 32 }, { hour: "11am", replies: 25 },
    { hour: "12pm", replies: 15 }, { hour: "1pm", replies: 8 }, { hour: "2pm", replies: 22 },
    { hour: "3pm", replies: 18 }, { hour: "4pm", replies: 14 }, { hour: "5pm", replies: 10 },
    { hour: "6pm", replies: 6 }, { hour: "7pm", replies: 3 }, { hour: "8pm", replies: 2 },
  ],
  Tue: [
    { hour: "6am", replies: 3 }, { hour: "7am", replies: 8 }, { hour: "8am", replies: 15 },
    { hour: "9am", replies: 35 }, { hour: "10am", replies: 38 }, { hour: "11am", replies: 28 },
    { hour: "12pm", replies: 12 }, { hour: "1pm", replies: 10 }, { hour: "2pm", replies: 25 },
    { hour: "3pm", replies: 20 }, { hour: "4pm", replies: 16 }, { hour: "5pm", replies: 12 },
    { hour: "6pm", replies: 5 }, { hour: "7pm", replies: 2 }, { hour: "8pm", replies: 1 },
  ],
  Wed: [
    { hour: "6am", replies: 1 }, { hour: "7am", replies: 4 }, { hour: "8am", replies: 10 },
    { hour: "9am", replies: 22 }, { hour: "10am", replies: 28 }, { hour: "11am", replies: 20 },
    { hour: "12pm", replies: 14 }, { hour: "1pm", replies: 9 }, { hour: "2pm", replies: 18 },
    { hour: "3pm", replies: 15 }, { hour: "4pm", replies: 12 }, { hour: "5pm", replies: 8 },
    { hour: "6pm", replies: 4 }, { hour: "7pm", replies: 2 }, { hour: "8pm", replies: 1 },
  ],
  Thu: [
    { hour: "6am", replies: 2 }, { hour: "7am", replies: 6 }, { hour: "8am", replies: 14 },
    { hour: "9am", replies: 30 }, { hour: "10am", replies: 34 }, { hour: "11am", replies: 24 },
    { hour: "12pm", replies: 12 }, { hour: "1pm", replies: 8 }, { hour: "2pm", replies: 20 },
    { hour: "3pm", replies: 16 }, { hour: "4pm", replies: 14 }, { hour: "5pm", replies: 10 },
    { hour: "6pm", replies: 5 }, { hour: "7pm", replies: 3 }, { hour: "8pm", replies: 2 },
  ],
  Fri: [
    { hour: "6am", replies: 1 }, { hour: "7am", replies: 3 }, { hour: "8am", replies: 8 },
    { hour: "9am", replies: 18 }, { hour: "10am", replies: 22 }, { hour: "11am", replies: 16 },
    { hour: "12pm", replies: 10 }, { hour: "1pm", replies: 6 }, { hour: "2pm", replies: 12 },
    { hour: "3pm", replies: 8 }, { hour: "4pm", replies: 6 }, { hour: "5pm", replies: 4 },
    { hour: "6pm", replies: 2 }, { hour: "7pm", replies: 1 }, { hour: "8pm", replies: 0 },
  ],
  Sat: [
    { hour: "6am", replies: 0 }, { hour: "7am", replies: 1 }, { hour: "8am", replies: 2 },
    { hour: "9am", replies: 4 }, { hour: "10am", replies: 6 }, { hour: "11am", replies: 5 },
    { hour: "12pm", replies: 4 }, { hour: "1pm", replies: 3 }, { hour: "2pm", replies: 4 },
    { hour: "3pm", replies: 3 }, { hour: "4pm", replies: 2 }, { hour: "5pm", replies: 1 },
    { hour: "6pm", replies: 0 }, { hour: "7pm", replies: 0 }, { hour: "8pm", replies: 0 },
  ],
  Sun: [
    { hour: "6am", replies: 0 }, { hour: "7am", replies: 0 }, { hour: "8am", replies: 1 },
    { hour: "9am", replies: 2 }, { hour: "10am", replies: 4 }, { hour: "11am", replies: 3 },
    { hour: "12pm", replies: 3 }, { hour: "1pm", replies: 2 }, { hour: "2pm", replies: 3 },
    { hour: "3pm", replies: 2 }, { hour: "4pm", replies: 1 }, { hour: "5pm", replies: 1 },
    { hour: "6pm", replies: 0 }, { hour: "7pm", replies: 0 }, { hour: "8pm", replies: 0 },
  ],
};

export const dailyReplyTypeData = [
  { date: "Jan 27", automated: 45, human: 28 },
  { date: "Jan 28", automated: 52, human: 35 },
  { date: "Jan 29", automated: 48, human: 31 },
  { date: "Jan 30", automated: 61, human: 42 },
  { date: "Jan 31", automated: 55, human: 38 },
  { date: "Feb 1", automated: 22, human: 12 },
  { date: "Feb 2", automated: 18, human: 8 },
  { date: "Feb 3", automated: 58, human: 40 },
  { date: "Feb 4", automated: 63, human: 45 },
  { date: "Feb 5", automated: 50, human: 32 },
];

export const hourlyReplyTypeData: Record<string, { hour: string; automated: number; human: number }[]> = {
  "Jan 27": [
    { hour: "6am", automated: 1, human: 0 }, { hour: "7am", automated: 2, human: 1 },
    { hour: "8am", automated: 4, human: 2 }, { hour: "9am", automated: 8, human: 5 },
    { hour: "10am", automated: 10, human: 6 }, { hour: "11am", automated: 7, human: 4 },
    { hour: "12pm", automated: 4, human: 3 }, { hour: "1pm", automated: 3, human: 2 },
    { hour: "2pm", automated: 6, human: 4 }, { hour: "3pm", automated: 5, human: 3 },
    { hour: "4pm", automated: 4, human: 2 }, { hour: "5pm", automated: 2, human: 1 },
  ],
  "Jan 28": [
    { hour: "6am", automated: 2, human: 1 }, { hour: "7am", automated: 3, human: 2 },
    { hour: "8am", automated: 5, human: 3 }, { hour: "9am", automated: 10, human: 7 },
    { hour: "10am", automated: 12, human: 8 }, { hour: "11am", automated: 8, human: 5 },
    { hour: "12pm", automated: 5, human: 3 }, { hour: "1pm", automated: 4, human: 2 },
    { hour: "2pm", automated: 7, human: 5 }, { hour: "3pm", automated: 6, human: 4 },
    { hour: "4pm", automated: 5, human: 3 }, { hour: "5pm", automated: 3, human: 2 },
  ],
  "Feb 5": [
    { hour: "6am", automated: 1, human: 1 }, { hour: "7am", automated: 3, human: 2 },
    { hour: "8am", automated: 5, human: 3 }, { hour: "9am", automated: 9, human: 6 },
    { hour: "10am", automated: 11, human: 7 }, { hour: "11am", automated: 8, human: 5 },
    { hour: "12pm", automated: 4, human: 2 }, { hour: "1pm", automated: 3, human: 2 },
    { hour: "2pm", automated: 6, human: 4 }, { hour: "3pm", automated: 5, human: 3 },
    { hour: "4pm", automated: 4, human: 2 }, { hour: "5pm", automated: 2, human: 1 },
  ],
};

export const espReplyRates = [
  {
    name: "Google to Google",
    data: [
      { date: "Jan 27", rate: 28.5 },
      { date: "Jan 28", rate: 31.2 },
      { date: "Jan 29", rate: 29.8 },
      { date: "Jan 30", rate: 33.4 },
      { date: "Jan 31", rate: 30.1 },
      { date: "Feb 1", rate: 25.6 },
      { date: "Feb 2", rate: 22.3 },
      { date: "Feb 3", rate: 32.8 },
      { date: "Feb 4", rate: 35.2 },
      { date: "Feb 5", rate: 31.5 },
    ],
    avgRate: 30.0,
  },
  {
    name: "Google to Outlook",
    data: [
      { date: "Jan 27", rate: 22.1 },
      { date: "Jan 28", rate: 24.5 },
      { date: "Jan 29", rate: 21.3 },
      { date: "Jan 30", rate: 26.8 },
      { date: "Jan 31", rate: 23.4 },
      { date: "Feb 1", rate: 19.2 },
      { date: "Feb 2", rate: 17.8 },
      { date: "Feb 3", rate: 25.1 },
      { date: "Feb 4", rate: 27.6 },
      { date: "Feb 5", rate: 24.2 },
    ],
    avgRate: 23.2,
  },
  {
    name: "Google to Custom",
    data: [
      { date: "Jan 27", rate: 18.3 },
      { date: "Jan 28", rate: 20.1 },
      { date: "Jan 29", rate: 17.5 },
      { date: "Jan 30", rate: 22.4 },
      { date: "Jan 31", rate: 19.8 },
      { date: "Feb 1", rate: 15.2 },
      { date: "Feb 2", rate: 13.6 },
      { date: "Feb 3", rate: 21.3 },
      { date: "Feb 4", rate: 23.8 },
      { date: "Feb 5", rate: 20.5 },
    ],
    avgRate: 19.3,
  },
  {
    name: "Outlook to Outlook",
    data: [
      { date: "Jan 27", rate: 26.4 },
      { date: "Jan 28", rate: 29.2 },
      { date: "Jan 29", rate: 27.1 },
      { date: "Jan 30", rate: 31.5 },
      { date: "Jan 31", rate: 28.3 },
      { date: "Feb 1", rate: 23.8 },
      { date: "Feb 2", rate: 20.5 },
      { date: "Feb 3", rate: 30.2 },
      { date: "Feb 4", rate: 33.1 },
      { date: "Feb 5", rate: 29.4 },
    ],
    avgRate: 28.0,
  },
  {
    name: "Outlook to Google",
    data: [
      { date: "Jan 27", rate: 24.8 },
      { date: "Jan 28", rate: 27.3 },
      { date: "Jan 29", rate: 25.6 },
      { date: "Jan 30", rate: 29.2 },
      { date: "Jan 31", rate: 26.1 },
      { date: "Feb 1", rate: 21.4 },
      { date: "Feb 2", rate: 18.9 },
      { date: "Feb 3", rate: 28.5 },
      { date: "Feb 4", rate: 30.8 },
      { date: "Feb 5", rate: 27.2 },
    ],
    avgRate: 26.0,
  },
  {
    name: "Outlook to Custom",
    data: [
      { date: "Jan 27", rate: 16.2 },
      { date: "Jan 28", rate: 18.5 },
      { date: "Jan 29", rate: 15.8 },
      { date: "Jan 30", rate: 20.3 },
      { date: "Jan 31", rate: 17.6 },
      { date: "Feb 1", rate: 13.1 },
      { date: "Feb 2", rate: 11.4 },
      { date: "Feb 3", rate: 19.2 },
      { date: "Feb 4", rate: 21.5 },
      { date: "Feb 5", rate: 18.1 },
    ],
    avgRate: 17.2,
  },
];
